### ISSUE TITLE
Local Development Issues

### ISSUE THREAD

**Issue by kakitzmiller** [ajaxray/php-watermark#7] opened 2018-04-30 20:21 UTC
I am getting the code to work exactly as I'd hoped on my live server.  I am using wamp locally, and it seems that the file isn't writing even though I'm using chmod on the directory and setting it to 0777.  Is there any reason I should think of why your code wouldn't write a new file on a windows server?

Thanks!
Kyle

**Comment by ajaxray** [comment] 2018-05-01 10:45
Thanks for asking.
Was there any error displayed?

**Comment by kakitzmiller** [comment] 2018-05-01 11:47
Nope, no error unfortunately, just a blank screen.  I've set the command to run on its own page for now so I can test, here's the code I'm running for now:

	//Assign/Create Folder
	$desination_folder_year = $_SERVER['DOCUMENT_ROOT'] . '/wp-content/uploads/user_downloads/' . date('Y');
	$desination_folder_month = $desination_folder_year . '/' . date('m');
	if(!file_exists($desination_folder_year)) mkdir($desination_folder_year);
	if(!file_exists($desination_folder_month)) mkdir($desination_folder_month);
	chmod($desination_folder_month, 0777);

	$original_file = $_SERVER['DOCUMENT_ROOT'] . '/wp-content/uploads/2018/04/test_document.pdf';

	$watermark = new Watermark($original_file);
	$watermark->setPosition(Watermark::POSITION_CENTER);
	$watermark->setOffset(0, 0);
	$watermark->setOpacity(.4);
	$image = get_stylesheet_directory() . '/assets/img/test_watermark.png';
	$watermark->withImage($image, $desination_folder_month . '/Tramack-' . time() . '.pdf');`

As mentioned, this code works as expected on the live server, I'm only having an issue with my local Windows environment.  Thanks in advance!

**Comment by Boss1669** [comment] 2018-05-10 11:05
Have you found a solution to this ?? I am experiencin as well

**Comment by ajaxray** [comment] 2018-05-13 15:57
Can you please set PHP to display all errors and then run it again?

You may add these lines on top of your file to enable error reporting:
```
error_reporting(E_ALL);
ini_set('display_errors', 1);
```

**Comment by kakitzmiller** [comment] 2018-05-14 09:06
I put the error reporting lines at the top of the page, and I don't receive any errors.  All I get is a blank screen, and the pdf isn't being generated.  I did however look in the php error log and found this:

```
[14-May-2018 08:59:46 UTC] PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, class 'PAnD' not found in C:\xampp\htdocs\ **WEBSITE_B** \wp-includes\class-wp-hook.php on line 286
[14-May-2018 08:59:46 UTC] PHP Stack trace:
[14-May-2018 08:59:46 UTC] PHP   1. {main}() C:\xampp\htdocs\ **WEBSITE_B** \wp-admin\admin-ajax.php:0
[14-May-2018 08:59:46 UTC] PHP   2. do_action() C:\xampp\htdocs\ **WEBSITE_B** \wp-admin\admin-ajax.php:44
[14-May-2018 08:59:46 UTC] PHP   3. WP_Hook->do_action() C:\xampp\htdocs\ **WEBSITE_B** \wp-includes\plugin.php:453
[14-May-2018 08:59:46 UTC] PHP   4. WP_Hook->apply_filters() C:\xampp\htdocs\ **WEBSITE_B** \wp-includes\class-wp-hook.php:310
```

As you can see, I've noted that it's trying to call the functions of a completely different site (which also exists on my WAMP server) even though I am running this function on WEBSITE_A.  The issue must be that it's calling something on the localhost without specifying which exact site.

Thanks!
Kyle

**Comment by ajaxray** [comment] 2018-05-17 10:20
@kakitzmiller ,
As you are confirming that the issue is not related to this library, I am closing this issue.
Thanks a lot for sharing your findings!

**Closed as completed by ajaxray** 2018-05-17 10:20 UTC
